### ISSUE TITLE
Параметр successUrl в Bill

### ISSUE THREAD

**Issue by megoRU** [osk115/Qiwi4J#2]
```JAVA
 
 Bill bill = Bill.builder()
                .amount(new BillAmount(BigDecimal.valueOf(value), BillAmount.Currency.RUB))
                .comment(comment)
                .successfulurl(url); // Нужно типа такого
                .expirationDateTime(ZonedDateTime.now().plusMinutes(30))
                .build();
                
 ```

**Comment by osk115** [comment]
К сожалению, возможности Qiwi4J ограничены функционалом официального API Qiwi, которое не имеет параметра `succesUrl` при выставление счета `server2server`. Параметр `succesUrl` передается только при создании формы p2p-оплаты ([`PaymentForm`](https://github.com/osk115/Qiwi4J/wiki/Классы-и-возвращаемые-объекты#paymentform))

❗ Обратите внимание, что пользователя переадресует на указанную ссылку только в случае успешной оплаты **с баланса** QIWI Кошелька. При ином способе оплаты **переадресация не выполняется**. Ссылка должна вести на сайт мерчанта. 


Подробнее в официальной документации:
* Выставление счета через форму: https://developer.qiwi.com/ru/p2p-payments/#http-invoice
* Выставление счета server2server: https://developer.qiwi.com/ru/bill-payments/#create
